# Prevention

We might try to prevent the exceptions generated by the system, but even if succeed in preventing it, how do we indicate that there was an issue?
For example with the input?


{% embed include file="src/examples/exceptions/preventing_divide_by_zero.py" %}



