Date(2013, 10, 20)
False
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    b = mydate.Date(2013, 13, 20)
  File "static_method/mydate.py", line 4, in __init__
    raise Exception('Invalid date')
Exception: Invalid date
