# PHPunit showing success



Just in order to see how it looks like I removed the failing test from the test script
and ran the test again.



the code

{% embed include file="src/examples/php/phpunit/calc02.php" %}

Output

{% embed include file="src/examples/php/phpunit/calc02.php.out" %}




