# Destructor delayed

Because the object has a reference to itself. (Python uses both reference count and garbage collection.)

{% embed include file="src/examples/oop/destructor_self_reference.py" %}
{% embed include file="src/examples/oop/destructor_self_reference.out" %}


